name: Update GitHub Metrics
on:
  schedule:
    - cron: "0 3 * * *" # runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JinreP
          template: classic
          filename: github-metrics.svg
          base: header, activity, repositories, metadata
          config_timezone: Asia/Ulaanbaatar
          output_action: commit
          committer_message: "chore: update metrics"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_followup: yes
