name: Update GitHub Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JinreP
          template: classic
          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"
          config_timezone: Asia/Ulaanbaatar

          base: header, activity, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_followup: yes

          # ✅ Add these at the bottom
          config_order: base.header, base.activity, base.repositories, base.metadata
          config_display: large
          config_optimistic_contribution_count: yes

