name: Update Streak Badge

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 03:00 UTC
  workflow_dispatch:
  # (optional) comment out the next 3 lines if you don't want auto-runs on push
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Generate streak.svg
        env:
          GH_STREAK_TOKEN: ${{ secrets.GH_STREAK_TOKEN }}
          STREAK_USER: JinreP
          STREAK_OUT: streak.svg         # ensure root output
        run: python .github/scripts/generate_streak_svg.py

      - name: Show repo contents
        run: |
          pwd
          ls -la

      - name: Verify artifact exists
        run: |
          if [ ! -f streak.svg ]; then
            echo "❌ streak.svg was not generated in $(pwd)"
            exit 1
          else
            echo "✅ streak.svg present"
          fi

      - name: Commit updated badge
        if: ${{ hashFiles('streak.svg') != '' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add streak.svg
          git commit -m "chore: update streak badge" || echo "No changes"
          git push
