name: Update Streak Badge

on:
  schedule:
    - cron: "0 3 * * *"      # daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # use GITHUB_TOKEN for push
          fetch-depth: 0              # allow committing new files

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Generate streak.svg
        env:
          GH_STREAK_TOKEN: ${{ secrets.GH_STREAK_TOKEN }}
          STREAK_USER: JinreP
          STREAK_OUT: streak.svg
        run: |
          python .github/scripts/generate_streak_svg.py
          echo "WORKSPACE=$GITHUB_WORKSPACE"
          echo "List after generation:"
          ls -la "$GITHUB_WORKSPACE"

      # Upload the SVG so we can view it even if commit fails
      - name: Upload artifact (streak.svg)
        if: exists('streak.svg')
        uses: actions/upload-artifact@v4
        with:
          name: streak-svg
          path: streak.svg

      - name: Commit & push streak.svg
        run: |
          set -e
          echo "PWD=$(pwd)"
          if [ ! -f "$GITHUB_WORKSPACE/streak.svg" ]; then
            echo "❌ streak.svg not found at $GITHUB_WORKSPACE"
            exit 1
          fi
          git status
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$GITHUB_WORKSPACE/streak.svg"
          git commit -m "chore: add/update streak.svg" || echo "No changes to commit"
          git push origin HEAD:main

